### ISSUE TITLE
First Beta Test of the Installation

### ISSUE THREAD

**Issue by diadeen** [zeryabmoussaoui/fuzzy-robot-type2#1]
Hello Sr , when I tried your project , I found an error although I put the files in the directory .I use MATLAB 2017b .Please could you help to solve this error ?

 
![e](https://user-images.githubusercontent.com/32939023/111877176-b63f9d00-89aa-11eb-9e79-5427823424f0.png)

**Comment by zeryabmoussaoui** [comment]
Hello, sorry for the issue.
You have to copy the  loadParameters to the ./data directory.
I add it to the github project.

**Comment by diadeen** [comment]
Thank you , I will try it .

**Comment by diadeen** [comment]
When I tried it I found error about this line :
save('/home/sagan/Projet_Navigation/data/Qtable.mat','Qtable')
I put it in  a comment and solve this issue, but I have a new error that explained in the picture : 

![e2](https://user-images.githubusercontent.com/32939023/111900781-1848e280-8a3d-11eb-99fc-f93625dca2be.png)

**Comment by zeryabmoussaoui** [comment]
I update the LoadParameters model, can you try it ?

Do you get the same issue when running the basic SimulationModel and the FLC1 ?

**Comment by diadeen** [comment]
Yes I use your  LoadParameters. It works good for FLC1 .
But I had that error only for T2FLC ! As you saw in the image .
Hint : I didn't find the T2FIS file in the folder ! Where is it to try other types of mfs or the rules ?

**Comment by zeryabmoussaoui** [comment]
There a another LoadParameters to try, i just commited it

**Comment by diadeen** [comment]
OK I will try it .

**Comment by diadeen** [comment]
I have got the same error ! Maybe I use MATLAB 2017b ? But please where is the file of FLC2 (t2fis_Avoidance) ? I think there is an error by the number on inputs and outputs of FLC2 ! Did you do any updates on the toolbox of IT2FLC ?

**Comment by diadeen** [comment]
![e3](https://user-images.githubusercontent.com/32939023/111913744-1f411680-8a78-11eb-8f63-a8f44bbbdcab.png)

**Comment by zeryabmoussaoui** [comment]
I did update the library(not recently) As said in the README You have to take my fork

**Comment by zeryabmoussaoui** [comment]
About the fis file. I will analyse that. Because yes there is fis file to add

**Comment by diadeen** [comment]
I tried your library for toolbox IT2FLC and the same error appeared !

**Comment by zeryabmoussaoui** [comment]
Can you show me where the missing file error appeared ?

**Comment by zeryabmoussaoui** [comment]
I cannot test because i didnt get a simulink licence.

Can you try this file ?

[IT2_avoidance.t2fis.zip](https://github.com/zeryabmoussaoui/fuzzy-robot-type2/files/6178298/IT2_avoidance.t2fis.zip)

t2fis_Avoidance=readt2fis('myfile.t2fis'); in your workpath

**Comment by diadeen** [comment]
Now it works , but the robot stopped after 20 sec and the Simulink halt on suddenly . I have to close MATLAB from the task manager!
![e4](https://user-images.githubusercontent.com/32939023/112018442-38f56300-8b37-11eb-8d96-a65f1aed9a2c.png)

**Comment by zeryabmoussaoui** [comment]
Great ! We are close !
Do you get any error ?
Can you load another scenario ? 
There must be a timeout in the code because the purpose of the project was to record .dat.
I cannot check because i didnt get licence.
That s why you have to test for me and i am sorry for That. 
You are the first to test installation.

**Comment by diadeen** [comment]
OK. I didn't get any errors ,except what I told you .
Could you send the Mfs and rules of FLC1 , I want to try to build as them in T2FLC .
And how to disable this file .dat to let the robot go to the target ?
Thank you and if there is any correct I have to do ,please tell me .

**Comment by zeryabmoussaoui** [comment]
I do need a licence to investigate. I will ask for a free licence to help you.
Do you try another scénario ?

**Comment by diadeen** [comment]
Yes ,I tried many scenarios , the problem is : 
When the robot turns on itself and doesn't find any target and find obstacles,  it halts on and doesn't move .
On the other hand by using T1FLC it goes and searches for the target .

**Comment by zeryabmoussaoui** [comment]
Can you send me all the variable of your workspace ? i will analyse that.
I will investigate when i get the free licence.

**Comment by zeryabmoussaoui** [comment]
There is another way : can i control your desktop remotely using TimeViewer ? We can organize a meeting.

**Comment by diadeen** [comment]
OK. I will use anydesk program for remote my desktop . Please email me for determined the time .

**Comment by zeryabmoussaoui** [comment]
Email me on zeryab.moussaoui@gmail.com

**Comment by zeryabmoussaoui** [comment]
Solved

**Comment by diadeen** [comment]
You save the time .
